provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  github-app-installations:
    lang: golang-middleware
    handler: ./github-app-installations
    image: github-app-installations:0.1

