[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "23.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
